# Generated by Django 2.0 on 2020-02-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
