# Generated by Django 2.0 on 2020-04-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20200223_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='month',
            field=models.CharField(max_length=7),
        ),
    ]
